default['linux']['user_id'] = 'user'
default['linux']['group'] = 'mygrp'
default['linux']['root'] = '/apps/linux-bin'
default['linux']['conf_root'] = '/apps/linux=apps'
#default['linux']['sec_root'] = '/opt/linuxSec'
